export const PRODUCTS = [
    { name: "Spaghetti Barilla 500g", price: 1.15, category: "Pâtes", inStock: true, description: "Pâtes au blé dur" },
    { name: "Riz Basmati Taureau Ailé 1kg", price: 3.50, category: "Riz", inStock: true, description: "Riz parfumé" },
    { name: "Sauce Tomate Panzani 400g", price: 1.80, category: "Sauces", inStock: true, description: "Sauce provençale" },
    { name: "Oeufs Bio x6", price: 2.90, category: "Frais", inStock: true, description: "Oeufs plein air" },
    { name: "Lait Demi-écrémé 1L", price: 1.05, category: "Frais", inStock: true, description: "Lait origine France" },
    { name: "Steak Haché 5% x2", price: 4.50, category: "Viande", inStock: true, description: "Boeuf charolais" },
    { name: "Beurre Doux Président 250g", price: 2.50, category: "Frais", inStock: true, description: "Beurre gastronomique" },
    { name: "Yaourt Nature Danone x4", price: 1.80, category: "Frais", inStock: true, description: "Yaourt au lait entier" },
    { name: "Pommes Golden 1kg", price: 2.20, category: "Fruits & Légumes", inStock: true, description: "Pommes origine France" },
    { name: "Bananes Cavendish 1kg", price: 1.50, category: "Fruits & Légumes", inStock: true, description: "Bananes import" },
    { name: "Carottes 1kg", price: 1.20, category: "Fruits & Légumes", inStock: true, description: "Carottes sable" },
    { name: "Poulet Fermier Label Rouge", price: 8.50, category: "Viande", inStock: true, description: "Poulet entier prêt à cuire" },
    { name: "Saumon Fumé Labeyrie 4 tranches", price: 6.90, category: "Poisson", inStock: true, description: "Saumon fumé de Norvège" },
    { name: "Pain de Mie Harrys", price: 1.30, category: "Boulangerie", inStock: true, description: "Pain de mie nature" },
    { name: "Jambon Blanc Herta x4", price: 3.20, category: "Charcuterie", inStock: true, description: "Jambon cuit à l'étouffée" },
    { name: "Coca-Cola 1.75L", price: 1.90, category: "Boissons", inStock: true, description: "Boisson gazeuse" },
    { name: "Jus d'Orange Joker 1L", price: 1.60, category: "Boissons", inStock: true, description: "Pur jus sans pulpe" },
    { name: "Chips Lay's Nature", price: 1.40, category: "Apéritif", inStock: true, description: "Chips de pommes de terre" },
    { name: "Chocolat Milka Lait", price: 1.10, category: "Epicerie Sucrée", inStock: true, description: "Tablette chocolat au lait" },
    { name: "Café Moulu Carte Noire 250g", price: 3.80, category: "Petit Déjeuner", inStock: true, description: "Café pur arabica" },
];
